### ISSUE TITLE
Story Component Not Found

### ISSUE THREAD

**Issue by onfranciis** [rgerum/unofficial-duolingo-stories#79]
I cloned this repository so that I could work on some issues and after running "npm run start" my webpack has refused to compile successfully.

![Screenshot from 2022-05-04 19-49-21](https://user-images.githubusercontent.com/96952305/166805360-f71b6da3-9ba2-4b59-a3c4-8b45a3490d1e.png)

The files on my local repository matches the ones on this master branch.

I observed this error on 3rd May, 2022 at 21:00 (GMT +0)

**Comment by rgerum** [comment]
I tried to move the story part outside into a subfolder. But I probably will need to refactor it again because I am not sure if that is the best solution to solve the problem of the editor-app and the stories-app using the story-component.

You should be able to
-run "npm install" in the editor-app folder
-run "npm install" in the story-component folder
-run "npm link ../editor-app/node_modules/react" in the story-component folder to ensure that both use the same copy of react.

I hope this helps. If not, you could try to checkout a previous version before the restructure.

**Comment by onfranciis** [comment]
I'll give it a try 

I would love to know what exactly you moved, and where exactly it was moved to
So that I would try getting a solution

**Comment by rgerum** [comment]
The folder story-component was previously in a subfolder of the editor-app
See
923b88151dbdb4051aac3cc1aacaaf9e0692e522

**Comment by onfranciis** [comment]
@rgerum  Just saw you did a lot of changes

Where can I start the development server ?

**Comment by onfranciis** [comment]
It's still having problems building

I want to help but **webpack.config.js** says no!

**Comment by rgerum** [comment]
maybe you could post your error log then I could have a look what the issue might be. Sorry for the inconvenience. I tried to do this restructuring to make it in the end easier to contribute.

**Comment by rgerum** [comment]
Ok I changed the information on how to run it in the Readme:
https://github.com/rgerum/unofficial-duolingo-stories/blob/master/README.md#how-to-run-locally
With these commands it should now run (save for the stories-app currently missing some font files which I will address later).

**Comment by rgerum** [comment]
Now I think it should be hopefully clear how to run things and also the automatic test should now run.
I will close this issue if it (hopefully) now runs smooth.
