### ISSUE TITLE
Learning-from language dropdown should be in native language

### ISSUE THREAD

**Issue by ptoro** [rgerum/unofficial-duolingo-stories#93]
It seems like the learning-from language dropdown on the homepage be in the language that the user speaks: e.g. instead of saying Greek, it should say "Ελληνικά". 
<img width="202" alt="image" src="https://user-images.githubusercontent.com/4418961/170178513-bc8bf96e-0d60-4d47-9d9e-fed0d0fb7cf3.png">

That way users intending to learn from another language don't need to know what their language is in English. This is also the way the Duolingo learning-from dropdown works: 
<img width="193" alt="image" src="https://user-images.githubusercontent.com/4418961/170178480-c49d6db4-f290-4d2b-bd85-a6d2d521f845.png">

**Comment by IFrzzl** [comment]
I don't think so - this is for learning from, not learning to. Since this is Greek from English, the Greek should say "Greek". However, the French from Russian should say "французский" as it does, so I don't see the problem.

**Comment by rgerum** [comment]
I think it does not make too much sense to put e.g. Greek in Greek if the course is Greek from English, or even Greek spelled in e.g. Polish because if the user does not recognize the word Greek they also cannot do too much with the course if all the questions and hints are in English.

Also having all language names translated into all languages can create quite a lot of pairs. Creating all of them is quite some effort with not too much benefit that I see. So if there are no more comments on this. I would close the issue.

What might be worth to think of is limiting the drop down menu to only feature the languages that have the same base language as the current one. Or only add languages that the user already has done at least one story in (e.g. courses that the user is using like in the Duolingo Dropdown menu)

**Comment by ptoro** [comment]
>Rupledo — Today at 3:15 PM
A button leading back to the homepage after you click a language might also not be a bad addition.

This supports the design idea in the previous comment where there's a DuoStories logo on the lefthand side of the page.

**Comment by ptoro** [comment]
Additional comments from Discord:

>Frzzl — Today at 3:25 PM
I do like the idea of adding something like in the second image tho
that could look quite nice
ptoro (Albanian Contributor) — Today at 3:25 PM
Definitely. Plus it would free up the space on the left to add a Duostories logo to allow users to get back to the homepage for language selection.
Frzzl — Today at 3:26 PM
absolutely.

**Comment by rgerum** [comment]
I have changed the dropdown menu to only contain the courses from which the (logged in) user has completed a story. To make it more in line with the Duolingo drop down menu where only courses the user has previously chosen are listed.
